FROM openjdk:8-jdk-stretch

MAINTAINER isfong@qq.com

ADD mycat /usr/local/mycat
RUN cd /usr/local && ls -lna

ENV MYCAT_HOME /usr/local/mycat
ENV PATH $MYCAT_HOME/bin:$PATH

VOLUME /usr/local/mycat/conf
VOLUME /usr/local/mycat/logs

EXPOSE 8066 9066

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak
ADD sources.list /etc/apt/
RUN apt update && apt install vim -y
ADD vimrc-append /
RUN cat /vimrc-append >> /etc/vim/vimrc



CMD ["/usr/local/mycat/bin/mycat", "console"]